coverage:
    status:
        project:
            default:
                target: auto
                threshold: 0%
                base: auto
        patch:
            default:
                target: 80%
                threshold: 0%
                base: auto
comment: 
    layout: "diff, files, footer"
    behavior: default
    require_changes: false
    require_head: true
    require_base: false
    hide_project_coverage: false

