# Step 1: build stage
FROM eclipse-temurin:25-jdk-alpine AS build
WORKDIR /app


# Install Maven
RUN apk add --no-cache maven bash git

# Copy project files
COPY pom.xml .
COPY src ./src

# Build the JAR
RUN mvn clean package -DskipTests

# Step 2: runtime stage
FROM eclipse-temurin:25-jdk-alpine
WORKDIR /app

COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080

ENTRYPOINT ["java","-jar","app.jar"]
